services:
  rmq:
    restart: always
    image: rabbitmq:4.1.0-management
#    ports:
#      - 5672:5672
#      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3

  redis:
    restart: always
    image: redis
 #   ports:
 #     - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  weather:
#    build:
#      context: ./services/weather
    image: ghcr.io/datew0/weather-prediction-weather:latest
    depends_on:
      rmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:80
    env_file:
      - ./.env

  forecast:
#    build:
#      context: ./services/forecast
    image: ghcr.io/datew0/weather-prediction-weather:latest
    env_file:
      - ./.env
    depends_on:
      rmq:
        condition: service_healthy
      redis:
        condition: service_healthy
